version: '2'
services:
  web:
    build:
      context: ./api_flask
      dockerfile: Dockerfile
    image: ponomarevsy/api_flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: ./api_db_model
      dockerfile: Dockerfile
    image: ponomarevsy/ml_models
    restart: always
    depends_on:
      - redis
  redis:
    image: redis




